---
# tasks file for nginx
    - name: Check OS Version
      debug: var=ansible_os_family

   - name: Update apt cache on Debian
      apt:
        update_cache: yes
    when: ansible_os_family == "Debian"

    - name: Install nginx on all systems
      package:
        name: nginx
        state: latest

    - name: Launch nginx 
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Create Nginx configuration file
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: Restart nginx

