---
# tasks file for mysql
    - name: Check OS Version
      debug: var=ansible_os_family

    - block: #====Block Ubuntu, CentOS====
      - name: Install mySQL on Ubuntu, CentOS
        apt:
          name: "{{ mysql_package_ubuntu }}"
          state: latest
          update_cache: yes
      when: (ansible_os_family=="Debian" and ansible_distribution=="Ubuntu") or ansible_os_family=="RadHat"

    - block: #====Block Debian====
      - name: Install mySQL on Debian
        apt:
          name: "{{ mysql_package_debian }}"
          state: latest
          update-cache: yes
      when: ansible_os_family=="Debian" and ansible_distribution=="Debian"

    - name: Launch mysql Debian, ubuntu
      service:
        name: "{{ mysql_service_debian }}"
        state: started
        enabled: yes


    - block: #====Block CentOS====
      - name: Launch nginx CentOS
        service:
          name: "{{ mysql_service_centos }}"
          state: started
      when: ansible_os_family=="RadHat"
