---
# tasks file for php
    - name: Check OS Version
      debug: var=ansible_os_family

    - block: #====Block Ubuntu, Debian, CentOs====
      - name: Install php packages
        package:
          name: "{{ item }}"
          state: present
        loop: "{{ php_packages }}"

      when: ansible_os_family in ['Debian', RedHat]

